version: "3.9"

services:

  backend:
    build: ./backend
    container_name: global_travel_backend
    restart: always

    ports:
      - "5000:5000"

    depends_on:
      - redis

    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: global_travel_frontend
    restart: always

    ports:
      - "6300:80"

    depends_on:
      - backend

  redis:
    image: redis:7
    container_name: redis
    restart: always

    ports:
      - "6379:6379"